global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "node-exporter-pi"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "node-exporter-backup-server"
    static_configs:
      - targets: ["100.92.156.184:9100"]

  - job_name: "home-assistant"
    metrics_path: /api/prometheus
    bearer_token_file: /etc/prometheus/secrets/ha_token
    static_configs:
      - targets: ["10.10.50.180:8123"]

  - job_name: "node-exporter-truenas"
    static_configs:
      - targets: ["10.10.20.220:9100"]

  - job_name: "pve"
    static_configs:
      - targets: ["10.10.10.5"]
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pve-exporter:9221

  - job_name: kube-state-metrics
    static_configs:
      - targets: ["10.10.20.100:30080"]
  - job_name: node-exporter
    static_configs:
      - targets: ["10.10.20.100:9100"]
  - job_name: traefik
    static_configs:
      - targets: ["10.10.20.100:30090"]
